version: '3'
services:
  web:
    image: olesb18/ikt206g24v06:latest # Using image from Docker Hub
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=assignment5;Username=hiphopgutt1;Password=hiphopgutt1;
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=assignment5
      - POSTGRES_USER=hiphopgutt1
      - POSTGRES_PASSWORD=hiphopgutt1
    volumes:
      - db_data:/var/lib/postgresql/data

  proxy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/config.json:/config.json
    command: --debug --interval 20 --label-enable --cleanup --notification email --notification-email-from watchtower@example.com --notification-email-to user@example.com --notification-email-server smtp.example.com --notification-email-server-port 587 --notification-email-server-user user@example.com --notification-email-server-password password
    environment:
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  db_data:
  caddy_data:
  caddy_config: